### ISSUE TITLE
复现结果请教

### ISSUE THREAD

**Issue by WuQiangXDU** [HaoTian-cn/TimesNet#1]
您好！我复现不出Timesnet论文中分类任务给出的结果，差很多，环境配置都是按照他们给出的。请问您有没有遇到这样的问题？

**Comment by HaoTian-cn** [comment]
> 您好！我复现不出Timesnet论文中分类任务给出的结果，差很多，环境配置都是按照他们给出的。请问您有没有遇到这样的问题？

你好，我暂时没有复现过他们的分类任务，我们做的模型在他们的基础上进行了有一定修改。具体细节你可以问问论文的原作者。

**Comment by HaoTian-cn** [comment]
> 您好！我复现不出Timesnet论文中分类任务给出的结果，差很多，环境配置都是按照他们给出的。请问您有没有遇到这样的问题？

你好，我暂时没有复现过他们的分类任务，我们做的模型在他们的基础上进行了有一定修改。具体细节你可以问问论文的原作者。

**Comment by WuQiangXDU** [comment]
> > 您好！我复现不出Timesnet论文中分类任务给出的结果，差很多，环境配置都是按照他们给出的。请问您有没有遇到这样的问题？
> 
> 你好，我暂时没有复现过他们的分类任务，我们做的模型在他们的基础上进行了有一定修改。具体细节你可以问问论文的原作者。

好的，谢谢！
